[package]
name = "rclrs_tests"
version = "0.3.1"
authors = ["Chris Reid <christopherjreid@outlook.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
test_msgs = "*"
quickcheck = "1"

[dependencies.rclrs]
version = "*"

[dependencies.rosidl_runtime_rs]
version = "*"
